spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.zglvfxqnackzjrqbysdk
    password: "AnmolMehla@6228"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or validate/create depending on your use case
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true